import { useEffect, useState } from 'react';
import { BlockNoteSchema, defaultBlockSpecs, insertOrUpdateBlockForSlashMenu } from '@blocknote/core';
import { createReactBlockSpec, getDefaultReactSlashMenuItems, SuggestionMenuController, useCreateBlockNote } from '@blocknote/react';
import { BlockNoteView } from '@blocknote/mantine';
import katex from 'katex';
import type { Page, PageBlock, StudyRecord, WidgetRecord } from '../shared/types';
import { prepareEditorBlocks, restoreUnknownBlocks, uid } from './logic';
import { BusyButton, Icon, Modal, useApp } from './ui';
import { StudyBlock, WidgetBlock } from './StudyTools';
const study=createReactBlockSpec({type:'study',propSchema:{recordId:{default:''},studyId:{default:''}},content:'none'},{render:({block})=><StudyBlock id={block.props.studyId||block.props.recordId}/>})();
const flashcards=createReactBlockSpec({type:'flashcards',propSchema:{studyId:{default:''},recordId:{default:''}},content:'none'},{render:({block})=><StudyBlock id={block.props.studyId||block.props.recordId}/>})();
const quiz=createReactBlockSpec({type:'quiz',propSchema:{studyId:{default:''},recordId:{default:''}},content:'none'},{render:({block})=><StudyBlock id={block.props.studyId||block.props.recordId}/>})();
const widget=createReactBlockSpec({type:'widget',propSchema:{recordId:{default:''},widgetId:{default:''}},content:'none'},{render:({block})=><WidgetBlock id={block.props.widgetId||block.props.recordId}/>})();
function Asset({id}:{id:string}) {const {snapshot,api,request}=useApp();const a=snapshot.assets.find(a=>a.id===id);const [url,setUrl]=useState(''),[previewError,setPreviewError]=useState('');useEffect(()=>{setUrl('');if(!a||!a.mime.startsWith('image/')||!api.isDesktop)return;let live=true;void api.request<{url:string}>('file.preview',{id}).then(result=>{if(live&&/^data:image\/(?:png|jpeg|gif|webp|avif|bmp);base64,/i.test(result.url))setUrl(result.url)}).catch(error=>{if(live)setPreviewError(error instanceof Error?error.message:String(error))});return ()=>{live=false}},[id,a?.mime,api]);if(!a)return <div className="asset-block muted" contentEditable={false}>Missing asset reference (preserved)</div>;return <div className="asset-block" contentEditable={false}>{url&&<button className="asset-image" onClick={()=>void request('file.open',{id:a.id}).catch(()=>{})}><img src={url} alt={a.name}/></button>}<Icon name={a.kind==='folder-link'?'ReaderIcon':'PaperPlaneIcon'}/><BusyButton action={()=>request('file.open',{id:a.id})}>{a.name}</BusyButton><small className="muted">{a.kind==='copy'?'Local copy':a.kind==='folder-link'?'Folder link':'File link'}</small><BusyButton action={()=>request('file.locate',{id:a.id})}>Locate</BusyButton>{previewError&&<small className="muted">{previewError}</small>}</div>}
const asset=createReactBlockSpec({type:'asset',propSchema:{assetId:{default:''}},content:'none'},{render:({block})=><Asset id={block.props.assetId}/>})();
const subpage=createReactBlockSpec({type:'subpage',propSchema:{pageId:{default:''}},content:'none'},{render:({block})=>{const {snapshot,openPage}=useApp();const p=snapshot.pages.find(p=>p.id===block.props.pageId);return <button contentEditable={false} className="subpage-block text-button" onClick={()=>p&&openPage(p.id)}><Icon name="FileTextIcon"/>{p?.title||'Untitled subpage'}</button>}})();
const equation=createReactBlockSpec({type:'equation',propSchema:{latex:{default:''}},content:'none'},{render:({block,editor})=>{const [edit,setEdit]=useState(false);const [value,setValue]=useState(block.props.latex);return <div className="equation-block" contentEditable={false}>{edit?<form onSubmit={e=>{e.preventDefault();editor.updateBlock(block,{props:{latex:value}});setEdit(false)}}><input autoFocus aria-label="Equation LaTeX" value={value} onChange={e=>setValue(e.target.value)}/><button>Save equation</button></form>:<button onClick={()=>setEdit(true)}>{block.props.latex?<span dangerouslySetInnerHTML={{__html:katex.renderToString(block.props.latex,{throwOnError:false,trust:false})}}/>:<span className="muted">Click to write an equation</span>}</button>}</div>}})();
const unsupported=createReactBlockSpec({type:'unsupported',propSchema:{originalType:{default:'unknown'},originalPayload:{default:''}},content:'none'},{render:({block})=><div className="unsupported-block" contentEditable={false}>Unsupported block: {block.props.originalType}. Original content is preserved.</div>})();
const {image: _image,file:_file,video:_video,audio:_audio,...writingSpecs}=defaultBlockSpecs;
export const editorSchema=BlockNoteSchema.create({blockSpecs:{...writingSpecs,study,flashcards,quiz,widget,asset,subpage,equation,unsupported}});
export const supportedTypes=new Set(Object.keys(editorSchema.blockSchema));
export const insertChoices=[['paragraph','Text','Writing'],['heading','Heading','Writing'],['toggleListItem','Toggle','Writing'],['bulletListItem','Bullet list','Lists & tables'],['numberedListItem','Numbered list','Lists & tables'],['checkListItem','To-do list','Lists & tables'],['table','Table','Lists & tables'],['codeBlock','Code','Writing'],['equation','Equation','Writing'],['image','Image','Files & links'],['file','File copy','Files & links'],['file-link','File or folder link','Files & links'],['subpage','Subpage','Files & links'],['flashcards','Flashcards','Study & tools'],['quiz','Quiz','Study & tools'],['widget','Interactive tool','Study & tools']] as const;
export function RichEditor({page,onChange,registerEditor,beforeInsert,onResourceInserted}:{page:Page;onChange:(blocks:PageBlock[])=>void;registerEditor:(editor:any)=>void;beforeInsert:()=>Promise<void>;onResourceInserted:(page:Page)=>void}) {const {snapshot,request,notify,openPage}=useApp();const [insertOpen,setInsertOpen]=useState(false),[search,setSearch]=useState(''),[linkOpen,setLinkOpen]=useState(false);const editor:any=useCreateBlockNote({schema:editorSchema as any,initialContent:page.blocks.length?prepareEditorBlocks(page.blocks,supportedTypes):[{type:'paragraph'}],uploadFile:async()=>{throw new Error('Use Insert → Image or File to choose an asset through the native app.')}});registerEditor(editor);
  const insert=async(type:string)=>{setInsertOpen(false);setSearch('');try{if(['file','image'].includes(type)){const a=await request<any>('file.attach',{pageId:page.id});if(a)(insertOrUpdateBlockForSlashMenu as any)(editor,{type:'asset',props:{assetId:a.id}});return}if(type==='file-link'){setLinkOpen(true);return}if(type==='subpage'){const child=await request<Page>('page.create',{parentId:page.id,title:''});(insertOrUpdateBlockForSlashMenu as any)(editor,{type:'subpage',props:{pageId:child.id}});return}if(type==='flashcards'||type==='quiz'){const record:StudyRecord={id:uid(),pageId:page.id,kind:type,title:type==='quiz'?'Quiz':'Flashcards',cards:type==='flashcards'?[{id:uid(),front:'',back:''}]:[],questions:type==='quiz'?[{id:uid(),prompt:'',type:'short-answer',answer:''}]:[],attempts:[],revision:1};await beforeInsert();const latest=(await request<any>('workspace.get')).pages.find((p:Page)=>p.id===page.id)!;const updated=await request<Page>('page.resource',{pageId:page.id,expectedRevision:latest.revision,kind:'study',record,block:{id:uid(),type,props:{studyId:record.id}}});onResourceInserted(updated);return}if(type==='widget'){const record:WidgetRecord={id:uid(),pageId:page.id,title:'Interactive tool',source:'<!doctype html><html><body style="font:14px system-ui;padding:16px"><p>Build an interactive exercise here.</p></body></html>',version:1,versions:[],state:{},revision:1};await beforeInsert();const latest=(await request<any>('workspace.get')).pages.find((p:Page)=>p.id===page.id)!;const updated=await request<Page>('page.resource',{pageId:page.id,expectedRevision:latest.revision,kind:'widget',record,block:{id:uid(),type:'widget',props:{widgetId:record.id}}});onResourceInserted(updated);return}if(type==='table'){(insertOrUpdateBlockForSlashMenu as any)(editor,{type:'table',content:{type:'tableContent',rows:[{cells:['','']},{cells:['','']}]}} as any)}else (insertOrUpdateBlockForSlashMenu as any)(editor,{type,props:type==='heading'?{level:2}:undefined} as any);editor.focus()}catch(e){notify(e instanceof Error?e.message:String(e))}};
  const slashItems=()=>[...getDefaultReactSlashMenuItems(editor),...insertChoices.filter(([type])=>['equation','image','file','file-link','subpage','flashcards','quiz','widget'].includes(type)).map(([type,title,group])=>({title,group,onItemClick:()=>void insert(type),aliases:[type]}))];
  const filtered=insertChoices.filter(([,title,group])=>`${title} ${group}`.toLowerCase().includes(search.toLowerCase()));
  return <><div className="insert-anchor"><button onClick={()=>setInsertOpen(!insertOpen)}><Icon name="PlusIcon"/>Insert<Icon name="ChevronDownIcon"/></button>{insertOpen&&<><div className="popover-dismiss" onClick={()=>setInsertOpen(false)}/><div className="insert-menu"><label className="search-input"><Icon name="MagnifyingGlassIcon"/><input autoFocus aria-label="Search blocks" placeholder="Search blocks…" value={search} onChange={e=>setSearch(e.target.value)}/></label>{['Writing','Lists & tables','Files & links','Study & tools'].map(group=><section key={group}>{filtered.some(x=>x[2]===group)&&<small className="muted">{group}</small>}{filtered.filter(x=>x[2]===group).map(([type,title])=><button key={type} onClick={()=>void insert(type)}><Icon name={type==='heading'?'HeadingIcon':type==='checkListItem'?'CheckboxIcon':type==='table'?'TableIcon':type==='widget'?'MagicWandIcon':type==='quiz'?'QuestionMarkCircledIcon':type==='flashcards'?'CopyIcon':type==='image'?'ImageIcon':'FileTextIcon'}/>{title}</button>)}</section>)}</div></>}</div><BlockNoteView editor={editor} theme="light" editable={page.status!=='trashed'} slashMenu={false} onChange={()=>onChange(restoreUnknownBlocks(editor.document as unknown as PageBlock[],page.blocks))}><SuggestionMenuController triggerCharacter="/" getItems={async query=>slashItems().filter(item=>`${item.title} ${(item.aliases??[]).join(' ')}`.toLowerCase().includes(query.toLowerCase()))}/></BlockNoteView>{linkOpen&&<Modal title="Attach a link" onClose={()=>setLinkOpen(false)}><p className="muted">Choose the file or folder in the desktop picker. Planner stores a selected asset reference.</p><footer><BusyButton action={async()=>{const a=await request<any>('file.link',{pageId:page.id});if(a)(insertOrUpdateBlockForSlashMenu as any)(editor,{type:'asset',props:{assetId:a.id}});setLinkOpen(false)}}>Choose file</BusyButton><BusyButton action={async()=>{const a=await request<any>('file.link',{pageId:page.id,folder:true});if(a)(insertOrUpdateBlockForSlashMenu as any)(editor,{type:'asset',props:{assetId:a.id}});setLinkOpen(false)}}>Choose folder</BusyButton></footer></Modal>}{snapshot.pages.filter(p=>p.parentId===page.id&&p.status!=='trashed').filter(p=>!page.blocks.some(b=>b.type==='subpage'&&b.props.pageId===p.id)).map(child=><button key={child.id} className="subpage-block text-button" onClick={()=>openPage(child.id)}><Icon name="FileTextIcon"/>{child.title||'Untitled subpage'}</button>)}</>;
}
