import { useEffect, useRef, useState } from 'react';
import type { StudyRecord, WidgetRecord } from '../shared/types';
import { BusyButton, IconButton, Modal, useApp } from './ui';
import { uid, saveAttemptAssessment } from './logic';
import { safePreviewToolSource } from './tool-policy';

export function StudyBlock({id}:{id:string}) {
  const {snapshot,request}=useApp();
  const record=snapshot.studies.find(study=>study.id===id),latest=record?.attempts.at(-1);
  const [index,setIndex]=useState(0),[revealed,setRevealed]=useState(false),[editing,setEditing]=useState(false);
  const [answers,setAnswers]=useState<Record<string,string>>(()=>latest?.answers??{}),[submitted,setSubmitted]=useState(Boolean(latest));
  const [assessment,setAssessment]=useState<Record<string,'again'|'got-it'>>(()=>latest?.selfAssessment??{}),[attemptId,setAttemptId]=useState<string|undefined>(latest?.id);
  const assessmentQueue=useRef<Promise<unknown>>(Promise.resolve());
  useEffect(()=>{const saved=record?.attempts.at(-1);setAnswers(saved?.answers??{});setAssessment(saved?.selfAssessment??{});setAttemptId(saved?.id);setSubmitted(Boolean(saved));setRevealed(false);setIndex(0)},[id,Boolean(record)]);
  if(!record)return <div className="tool-block muted">Study record unavailable. Its reference is preserved.</div>;
  const card=record.cards[index%Math.max(record.cards.length,1)];
  const save=async(changes:Partial<StudyRecord>)=>request('study.save',{record:{...record,...changes},expectedRevision:record.revision});
  const attempt=async()=>{
    const mc=record.questions.filter(question=>question.type==='multiple-choice');
    const score=mc.length?mc.filter(question=>answers[question.id]===question.answer).length/mc.length:undefined;
    const newAttempt={id:uid(),at:new Date().toISOString(),answers:{...answers},selfAssessment:{...assessment},score};
    await save({attempts:[...record.attempts,newAttempt]});setAttemptId(newAttempt.id);setSubmitted(true);
  };
  const assess=async(questionId:string,value:'again'|'got-it')=>{
    if(submitted){
      if(!attemptId)throw new Error('Save an attempt before adding feedback.');
      const selectedAttempt=attemptId;
      const saving=assessmentQueue.current.catch(()=>{}).then(()=>saveAttemptAssessment(request,id,selectedAttempt,questionId,value));
      assessmentQueue.current=saving;await saving;
    }
    setAssessment(current=>({...current,[questionId]:value}));
  };
  return <div className="tool-block" contentEditable={false}><div className="tool-heading"><strong>{record.title|| (record.kind==='flashcards'?'Flashcards':'Quiz')}</strong><button onClick={()=>setEditing(true)}>Edit</button></div>
    {record.kind==='flashcards'?card?<><div className="muted">{index+1} / {record.cards.length}</div><p className="card-prompt">{card.front||'Add a question'}</p>{revealed&&<p className="card-answer">{card.back||'No answer yet'}</p>}<div className="tool-actions">{!revealed?<button onClick={()=>setRevealed(true)}>Reveal answer</button>:<><BusyButton action={async()=>{await save({cards:record.cards.map(item=>item.id===card.id?{...item,review:'again',reviewedAt:new Date().toISOString()}:item)});setIndex((index+1)%record.cards.length);setRevealed(false)}}>Again</BusyButton><BusyButton action={async()=>{await save({cards:record.cards.map(item=>item.id===card.id?{...item,review:'got-it',reviewedAt:new Date().toISOString()}:item)});setIndex((index+1)%record.cards.length);setRevealed(false)}}>Got it</BusyButton></>}<IconButton name="ChevronRightIcon" label="Next card" onClick={()=>{setIndex((index+1)%record.cards.length);setRevealed(false)}}/><button onClick={()=>{const missed=record.cards.findIndex(item=>item.review==='again');setIndex(missed>=0?missed:0);setRevealed(false)}}>Retry missed</button></div></>:<p className="muted">Add cards to start practicing.</p>:<>
      <div className="quiz-questions">{record.questions.map((question,i)=><div key={question.id} className="quiz-question"><strong>{i+1}. {question.prompt}</strong>{question.type==='multiple-choice'?<div className="quiz-choices">{question.choices?.map((choice,j)=><label key={j}><input disabled={submitted} type="radio" name={`${id}-${question.id}`} checked={answers[question.id]===choice} onChange={()=>setAnswers({...answers,[question.id]:choice})}/>{choice}</label>)}</div>:<textarea disabled={submitted} aria-label={`Answer to question ${i+1}`} value={answers[question.id]??''} onChange={event=>setAnswers({...answers,[question.id]:event.target.value})}/>}{(revealed||submitted)&&<div className="quiz-answer"><p>{question.type==='multiple-choice'&&submitted?(answers[question.id]===question.answer?'Correct. ':'Try this again. '):''}{question.answer}</p>{question.explanation&&<small>{question.explanation}</small>}{question.type==='short-answer'&&<div className="tool-actions"><BusyButton className={assessment[question.id]==='again'?'selected':''} action={()=>assess(question.id,'again')}>Needs another attempt</BusyButton><BusyButton className={assessment[question.id]==='got-it'?'selected':''} action={()=>assess(question.id,'got-it')}>Got it</BusyButton></div>}</div>}</div>)}</div>
      {record.questions.length>0&&<div className="tool-actions">{!submitted&&<><button onClick={()=>setRevealed(true)}>Reveal for self-assessment</button><BusyButton action={async()=>{if(record.questions.some(question=>!answers[question.id]?.trim()))throw new Error('Answer every question before submitting');await attempt()}}>Submit answers & save attempt</BusyButton></>}{submitted&&<span className="muted">Attempt and feedback saved.</span>}<button onClick={()=>{setAnswers({});setAssessment({});setAttemptId(undefined);setSubmitted(false);setRevealed(false)}}>Retry</button><small className="muted">{record.attempts.length} saved attempts</small></div>}
      {!!record.attempts.length&&<details className="quiz-history"><summary>Saved attempts</summary>{record.attempts.map(saved=><button key={saved.id} className="text-button" onClick={()=>{setAnswers(saved.answers);setAssessment(saved.selfAssessment??{});setAttemptId(saved.id);setSubmitted(true);setRevealed(true)}}>{new Date(saved.at).toLocaleString()}{saved.score!==undefined?` · ${Math.round(saved.score*100)}%`:''}</button>)}</details>}
      {!record.questions.length&&<p className="muted">Add questions to start a quiz.</p>}
    </>}{editing&&<StudyEditor record={record} onClose={()=>setEditing(false)}/>}</div>;
}
function StudyEditor({record,onClose}:{record:StudyRecord;onClose:()=>void}) {const {request}=useApp();const [draft,setDraft]=useState(structuredClone(record));return <Modal title={`Edit ${record.kind==='flashcards'?'flashcards':'quiz'}`} onClose={onClose}><label>Title<input value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><div className="study-editor-items">{draft.kind==='flashcards'?draft.cards.map((card,i)=><div key={card.id} className="study-edit-item"><label>Front<textarea value={card.front} onChange={e=>setDraft({...draft,cards:draft.cards.map((c,j)=>j===i?{...c,front:e.target.value}:c)})}/></label><label>Back<textarea value={card.back} onChange={e=>setDraft({...draft,cards:draft.cards.map((c,j)=>j===i?{...c,back:e.target.value}:c)})}/></label><button onClick={()=>setDraft({...draft,cards:draft.cards.filter(c=>c.id!==card.id)})}>Remove card</button></div>):draft.questions.map((q,i)=><div key={q.id} className="study-edit-item"><label>Question<textarea value={q.prompt} onChange={e=>setDraft({...draft,questions:draft.questions.map((v,j)=>j===i?{...v,prompt:e.target.value}:v)})}/></label><label>Question type<select value={q.type} onChange={e=>setDraft({...draft,questions:draft.questions.map((v,j)=>j===i?{...v,type:e.target.value as any,choices:e.target.value==='multiple-choice'?(v.choices??['','']):undefined}:v)})}><option value="short-answer">Short answer</option><option value="multiple-choice">Multiple choice</option></select></label>{q.type==='multiple-choice'&&<label>Choices (one per line)<textarea value={q.choices?.join('\n')??''} onChange={e=>setDraft({...draft,questions:draft.questions.map((v,j)=>j===i?{...v,choices:e.target.value.split('\n')}:v)})}/></label>}<label>Answer<textarea value={q.answer} onChange={e=>setDraft({...draft,questions:draft.questions.map((v,j)=>j===i?{...v,answer:e.target.value}:v)})}/></label><label>Explanation<textarea value={q.explanation??''} onChange={e=>setDraft({...draft,questions:draft.questions.map((v,j)=>j===i?{...v,explanation:e.target.value}:v)})}/></label><button onClick={()=>setDraft({...draft,questions:draft.questions.filter(v=>v.id!==q.id)})}>Remove question</button></div>)}</div><button onClick={()=>setDraft(draft.kind==='flashcards'?{...draft,cards:[...draft.cards,{id:uid(),front:'',back:''}]}:{...draft,questions:[...draft.questions,{id:uid(),prompt:'',type:'short-answer',answer:''}]})}>Add {draft.kind==='flashcards'?'card':'question'}</button><footer><button onClick={onClose}>Cancel</button><BusyButton action={async()=>{if(draft.questions.some(q=>q.type==='multiple-choice'&&!q.choices?.includes(q.answer)))throw new Error('Each multiple-choice answer must match one of its choices');await request('study.save',{record:draft,expectedRevision:record.revision});onClose()}}>Save</BusyButton></footer></Modal>}
export function WidgetBlock({id}:{id:string}) {const {snapshot,api,request,notify}=useApp();const widget=snapshot.widgets.find(w=>w.id===id),ref=useRef<HTMLDivElement>(null);const [running,setRunning]=useState(false),[edit,setEdit]=useState(false),[error,setError]=useState('');
  useEffect(()=>{
    if(!widget||!api.isDesktop||!running)return;
    let disposed=false,mounted=false;
    const sync=async()=>{
      const surface=ref.current,r=surface?.getBoundingClientRect();if(!surface||!r||disposed)return;
      const viewport=surface.closest('.main-content')?.getBoundingClientRect();
      const left=Math.max(0,r.left,viewport?.left??0),right=Math.min(r.right,window.innerWidth,viewport?.right??window.innerWidth);
      const top=Math.max(r.top,48,viewport?.top??48),bottom=Math.min(r.bottom,window.innerHeight,viewport?.bottom??window.innerHeight);
      const bounds={x:Math.round(left),y:Math.round(top),width:Math.round(Math.max(0,right-left)),height:Math.round(Math.max(0,bottom-top))};
      try{await api.request(mounted?'widget.bounds':'widget.mount',{id,bounds});mounted=true}catch(e){if(!disposed){setError(e instanceof Error?e.message:String(e));setRunning(false)}}
    };
    void sync();
    const observer=new ResizeObserver(()=>void sync());
    if(ref.current){observer.observe(ref.current);for(const selector of ['.main-content','.page-document']){const ancestor=ref.current.closest(selector);if(ancestor)observer.observe(ancestor)}}
    window.addEventListener('resize',sync);window.addEventListener('scroll',sync,true);
    return ()=>{disposed=true;observer.disconnect();window.removeEventListener('resize',sync);window.removeEventListener('scroll',sync,true);void api.request('widget.unmount',{id}).catch(()=>{})};
  },[id,api,running,widget?.version]);
  if(!widget)return <div className="tool-block muted">Tool record unavailable. Reference preserved.</div>;
  return <div className="tool-block widget" contentEditable={false}><div className="tool-heading"><strong>{widget.title||'Interactive tool'}</strong><span className="muted">Version {widget.version}</span><button onClick={()=>setEdit(true)}>Source</button></div>{error&&<p className="error-message">{error}</p>}<div ref={ref} className="widget-surface">{running?(api.isDesktop?<span className="muted">Native tool surface</span>:<iframe title={widget.title||'Browser preview tool'} sandbox="allow-scripts" srcDoc={safePreviewToolSource(widget.source)}/>):<p className="muted">{api.isDesktop?'Start this tool to open its isolated surface.':'Browser preview: sandboxed local iframe; native widget isolation is unavailable.'}</p>}</div><div className="tool-actions"><BusyButton action={async()=>{setError('');if(running&&api.isDesktop)await request('widget.reload',{id});else setRunning(true)}}>{running?'Reload':'Start'}</BusyButton><BusyButton action={async()=>{if(api.isDesktop)await request('widget.stop',{id});setRunning(false)}}>Stop</BusyButton>{widget.versions.length>0&&<select aria-label="Revert tool version" defaultValue="" onChange={async e=>{if(!e.target.value)return;try{if(api.isDesktop)await request('widget.revert',{id,version:Number(e.target.value)});else {const old=widget.versions.find(v=>v.version===Number(e.target.value))!;await request('widget.save',{record:{...widget,source:old.source,version:widget.version+1},expectedRevision:widget.revision})}}catch(error){notify(String(error))}e.target.value=''}}><option value="">Revert version…</option>{widget.versions.map(v=><option key={v.version} value={v.version}>Version {v.version}</option>)}</select>}</div>{edit&&<WidgetEditor widget={widget} onClose={()=>setEdit(false)}/ >}</div>
}
function WidgetEditor({widget,onClose}:{widget:WidgetRecord;onClose:()=>void}) {const {request}=useApp();const [source,setSource]=useState(widget.source),[title,setTitle]=useState(widget.title);return <Modal title="Tool source" onClose={onClose}><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>HTML source<textarea className="source-editor" spellCheck={false} value={source} onChange={e=>setSource(e.target.value)}/></label><p className="muted">This local HTML tool runs in a separate surface. Use the assistant to build a diagram or exercise from your page.</p><footer><button onClick={onClose}>Cancel</button><BusyButton action={async()=>{await request('widget.save',{record:{...widget,title,source,version:widget.version+1,versions:[...widget.versions,{version:widget.version,source:widget.source}]},expectedRevision:widget.revision});onClose()}}>Save version</BusyButton></footer></Modal>}
