import { createContext, useContext, useState, useEffect, useRef, type ReactNode } from 'react';
import type { PlannerAPI, WorkspaceSnapshot } from '../shared/types';
import * as Icons from '@radix-ui/react-icons';
export type IconName = keyof typeof Icons;
export function Icon({name,size=16}:{name:IconName;size?:number}) {const C=Icons[name] as any;return <C width={size} height={size}/>}
export function IconButton({name,label,onClick,active=false,disabled=false}:{name:IconName;label:string;onClick?:()=>void;active?:boolean;disabled?:boolean}) {return <button className={`icon-button ${active?'active':''}`} title={label} aria-label={label} onClick={onClick} disabled={disabled}><Icon name={name}/></button>}
export interface AppContextValue {snapshot:WorkspaceSnapshot;api:PlannerAPI;request:<T=unknown>(method:string,params?:Record<string,unknown>)=>Promise<T>;openPage:(id:string,blockId?:string)=>void;refresh:()=>Promise<void>;flushPage:()=>Promise<void>;notify:(message:string)=>void;registerNavigationGuard:(guard:()=>Promise<void>)=>()=>void}
export const AppContext=createContext<AppContextValue|null>(null);
export function useApp(){const value=useContext(AppContext);if(!value)throw new Error('Workspace unavailable');return value}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}) {
  const dialog=useRef<HTMLElement>(null),close=useRef(onClose);close.current=onClose;
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const node=dialog.current;if(!node)return;const candidates=()=>Array.from(node.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href],[tabindex="0"]')).filter(el=>el.offsetParent!==null);const first=candidates()[0];if(!node.contains(document.activeElement))first?.focus();const key=(event:KeyboardEvent)=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();close.current();return}if(event.key!=='Tab')return;const list=candidates(),first=list[0],last=list.at(-1);if(!first){event.preventDefault();node.focus()}else if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}};node.addEventListener('keydown',key);return()=>{node.removeEventListener('keydown',key);previous?.isConnected&&previous.focus()}},[]);
  return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section ref={dialog} tabIndex={-1} className="modal" role="dialog" aria-modal="true" aria-label={title}><header><strong>{title}</strong><IconButton name="Cross2Icon" label="Close" onClick={onClose}/></header>{children}</section></div>
}
export function BusyButton({children,action,className=''}:{children:ReactNode;action:()=>Promise<unknown>;className?:string}) {const [busy,setBusy]=useState(false);const {notify}=useApp();return <button className={className} disabled={busy} onClick={async()=>{setBusy(true);try{await action()}catch(e){notify(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}}>{busy?'Working…':children}</button>}
